feat: Disable the "reported by reviewdog 🐶" Prefix in Review Messages
reviewdog/reviewdog pull request #1667
Opened 2024-02-09 15:13 UTC by Okabe-Junya

close #1662 

- [ ] Updated Unreleased section in [CHANGELOG](https://github.com/reviewdog/reviewdog/blob/master/CHANGELOG.md) or it's not notable changes.

## Change List

- delete: the prefix "reported by reviewdog 🐶" whenever reviewdog comment
- update: README

2024-02-09 15:51 UTC, haya14busa requested changes
I do not plan to disable it without any config at least.

2024-02-09 15:54 UTC, Okabe-Junya commented
Thank you :)

I apologize for making such a change in the PR. I would like to modify it so that it can be disabled using the appropriate flags (e.g., `disable-prefix`)

2024-06-08 10:16 UTC, closed without merging

2024-06-08 10:16 UTC, haya14busa commented
Please reopen if needed.

2024-06-08 17:43 UTC, Okabe-Junya commented
I am very sorry. I will create a new PR when working on any issues, thank you!!