Fix for suggestions not including an inserted EOF newline
reviewdog/reviewdog pull request #1975
Opened 2024-11-25 17:11 UTC by dallonf

When an end-of-file newline is inserted, Reviewdog currently doesn't include it in the resulting suggestion, often resulting in a diff (ex. as a GitHub PR review) that can't be applied because there are no actual changes suggested.

See #1927.

This adds some smarter handling of EOF newlines into the Diff Hunk parser, as well as special-case handling into Suggestion generation, and a handful of tests for both.

Happy to make revisions; I'm pretty green in Go.

- [x] Updated Unreleased section in [CHANGELOG](https://github.com/reviewdog/reviewdog/blob/master/CHANGELOG.md) or it's not notable changes.

2025-02-04 07:36 UTC, haya14busa commented
sry for the late review. See https://github.com/reviewdog/reviewdog/issues/1927#issuecomment-2633099908

2025-02-04 07:37 UTC, haya14busa commented
The change itself looks good, but i'm not sure it's worth including it if it doesn't solve the problem.

2025-02-04 14:01 UTC, dallonf commented
Why do you say it doesn't solve the problem? In my personal tests, it identifies that a newline has been added by reviewdog and adds it to the suggestion.

2025-02-04 16:07 UTC, dallonf commented on parser/diff_test.go
> +}
```suggestion
}

```

2025-02-04 16:07 UTC, dallonf commented on diff_test.go
> +}
```suggestion
}

```

@haya14busa as requested

2025-02-04 18:16 UTC, haya14busa commented on diff_test.go
> +}
> We could think of inserting new blank line at the end alternatively like the above, but it's obviously different suggestion and unintended behabior.
>
> https://github.com/reviewdog/reviewdog/issues/1927#issuecomment-2633099908

This suggestion adds a new blank line, instead of adding EOF new line.

2025-02-04 19:04 UTC, dallonf commented on diff_test.go
> +}
If I commit it, I'm fairly certain it will add a EOF newline, even though it appears to be a blank line here

2025-02-04 19:05 UTC, dallonf commented
@haya14busa See the commit made when accepting the suggestion: it does in fact add an EOF newline instead of a blank line. https://github.com/reviewdog/reviewdog/pull/1975/commits/6723f3877ddae637bc8a0b92e139adce5992da74

2025-02-05 05:58 UTC, haya14busa requested changes

2025-02-05 05:58 UTC, haya14busa commented on parser/diff.go
> +				state.newLines = append(state.newLines, "")
Can you add a comment and a link to the PR comment so that future readers can understand it resolves the issue with GitHub suggestions.

Note that we don't confirm it works in the same way with other reporter such as GitLab, BitBucket etc...
Especially, I plan to add a feature that reviewdog could apply suggestions in local envorinment.
Then, this change won't work as expected for such other reporters. 
We should leave a comment about it.
Alternatively, it would be great if we can move the logic to GitHub review comment reporter.

2025-02-05 05:58 UTC, haya14busa commented on parser/diff.go
> +				// TODO: also handle the much rarer case of a deleted eof newline
[nit] I think we don't have a clear plan/TODO to support deleting EOF newline.
I prefer mark it as `NOTE:` or something because it's actually not in our TODO list.

2025-02-05 06:00 UTC, haya14busa commented
> @haya14busa See the commit made when accepting the suggestion: it does in fact add an EOF newline instead of a blank line. [6723f38](https://github.com/reviewdog/reviewdog/commit/6723f3877ddae637bc8a0b92e139adce5992da74)

Thanks! It's interesting that GitHub actually doesn't add new blank line. I was not aware of it. Nice finding! :+1:

2025-02-05 16:04 UTC, dallonf commented
Went ahead and made those requested comment changes. I don't really know the codebase well enough to make it work just for GitHub, but I can revisit if it turns out to be an issue (ping me 😄).

Personally, my hunch is that most reporters will behave in the desired way - after all, what is an EOF newline but a blank line at the end of the file?

2025-02-08 05:02 UTC, haya14busa approved these changes

2025-02-08 05:02 UTC, merged

2025-02-08 05:02 UTC, review-dog commented
Hi, @dallonf! We merged your PR to reviewdog! 🐶
Thank you for your contribution! ✨

**We just invited you to join the @reviewdog organization on GitHub.**
Accept the invite by visiting https://github.com/orgs/reviewdog/invitation.
By joining the team, you'll be a part of reviewdog community and can help the maintenance of reviewdog.

Thanks again!
<!-- This invitation is generated by https://github.com/reviewdog/inviter -->

2025-02-08 05:03 UTC, haya14busa commented
Thank you for your contribution! ✨

2025-04-05 07:49 UTC, facusapienza21 commented
I just encounter this same issue! Thank you for the fix. Is there any new release coming so these changes do propagate to the latest version? Thanks!